[tool.poetry]
name = "skin-cancer-detection"
version = "0.1.0"
description = ""
authors = ["razodan <d.antonio.razo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13.5"
tensorflow = "^2.21.0"
numpy = "^2.4.3"
pandas = "^3.0.1"
scikit-learn = "^1.8.0"
pillow = "^12.1.1"
matplotlib = "^3.10.8"
seaborn = "^0.13.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
